import React,{useEffect,useRef,useState} from 'react';
import {type Layer,type Slide,safeLink} from '../../presentation-schema/src/model';

export function Scene({slide,onSelect,selected=[],interactive=false,playToken=0}:{slide:Slide;onSelect?:(id:string)=>void;selected?:string[];interactive?:boolean;playToken?:number}){
  const host=useRef<HTMLDivElement>(null);const[scale,setScale]=useState(.4);
  useEffect(()=>{if(!host.current)return;const observer=new ResizeObserver(([entry])=>setScale(Math.min(entry.contentRect.width/slide.width,entry.contentRect.height/slide.height)));observer.observe(host.current);return()=>observer.disconnect();},[slide.width,slide.height]);
  useEffect(()=>{if(!playToken||!host.current)return;const running:Animation[]=[];for(const layer of flatten(slide.layers)){const element=host.current.querySelector<HTMLElement>(`[data-layer-id="${CSS.escape(layer.id)}"]`);if(!element)continue;for(const motion of layer.meta.animations)running.push(element.animate(keyframes(motion.effect,motion.distance),{duration:motion.duration,delay:motion.delay,easing:motion.easing,fill:'both'}));}return()=>running.forEach(animation=>animation.cancel());},[playToken,slide]);
  function render(layer:Layer){return <div key={layer.id} className='layer-position' style={{position:'absolute',left:layer.x,top:layer.y,width:layer.width,height:layer.height,transform:'rotate('+layer.rotation+'deg)',transformOrigin:'top left',opacity:layer.opacity}}><div data-layer-id={layer.id} onClick={event=>{event.stopPropagation();onSelect?.(layer.id);if(interactive&&safeLink(layer.meta.url))window.open(safeLink(layer.meta.url),'_blank','noopener,noreferrer');}} style={{width:'100%',height:'100%',outline:selected.includes(layer.id)?'3px solid #ff2934':undefined,cursor:onSelect?'pointer':undefined,background:layer.asset?'transparent':layer.fill,borderRadius:layer.radius}}>{interactive&&layer.meta.video&&/^https:\/\//.test(layer.meta.video)?<video src={layer.meta.video} style={{width:'100%',height:'100%'}} controls muted={layer.meta.muted} loop={layer.meta.loop} autoPlay={layer.meta.autoplay}/>:layer.asset?<img draggable={false} src={layer.asset} style={{width:'100%',height:'100%',display:'block'}}/>:layer.text?<div style={{fontFamily:layer.fontFamily,fontSize:layer.fontSize,fontWeight:layer.fontWeight,color:layer.fill,whiteSpace:'pre-wrap'}}>{layer.text}</div>:null}{layer.children.map(render)}</div></div>;}
  return <div className='scene-host' ref={host}><div className='scene' style={{width:slide.width,height:slide.height,background:slide.background,transform:'translate(-50%,-50%) scale('+scale+')'}}>{slide.layers.map(render)}</div></div>;
}

function flatten(layers:Layer[]):Layer[]{return layers.flatMap(layer=>[layer,...flatten(layer.children)]);}
function keyframes(effect:string,distance:number):Keyframe[]{const end:Keyframe={opacity:1,transform:'translate3d(0,0,0) scale(1) rotate(0deg)',filter:'blur(0)',clipPath:'inset(0 0 0 0)'};const starts:Record<string,Keyframe>={fade:{opacity:0},'fade-up':{opacity:0,transform:`translateY(${distance}px)`},'fade-down':{opacity:0,transform:`translateY(-${distance}px)`},'fade-left':{opacity:0,transform:`translateX(${distance}px)`},'fade-right':{opacity:0,transform:`translateX(-${distance}px)`},zoom:{opacity:0,transform:'scale(.72)'},pop:{opacity:0,transform:'scale(.55)'},rotate:{opacity:0,transform:'rotate(-16deg) scale(.9)'},flip:{opacity:0,transform:'perspective(900px) rotateY(-80deg)'},blur:{opacity:0,filter:'blur(18px)'},wipe:{opacity:0,clipPath:'inset(0 100% 0 0)'},bounce:{opacity:0,transform:`translateY(${distance}px)`},pulse:{transform:'scale(.9)'},shake:{transform:'translateX(-10px)'}};const start=starts[effect]??{opacity:0};if(effect==='pulse')return[start,{transform:'scale(1.06)',offset:.5},end];if(effect==='shake')return[start,{transform:'translateX(10px)',offset:.25},{transform:'translateX(-7px)',offset:.55},end];return[start,end];}
