import {PDFDocument} from 'pdf-lib';
import PptxGenJS from 'pptxgenjs';
import JSZip from 'jszip';
import {request} from './bridge';
import type {Layer,Slide} from '../../../packages/presentation-schema/src/model';

type RasterSlide={name:string;width:number;height:number;bytes:Uint8Array};
const clean=(name:string)=>name.replace(/[<>:"/\\|?*\u0000-\u001f]/g,'-').trim()||'presentation';
function download(data:BlobPart|Uint8Array,type:string,name:string){const part:BlobPart=data instanceof Uint8Array?new Uint8Array(data).buffer:data;const url=URL.createObjectURL(new Blob([part],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function raster(ids:string[],quality:number,onProgress:(message:string)=>void){const slides:RasterSlide[]=[];for(let i=0;i<ids.length;i++){onProgress(`Renderizando slide ${i+1}/${ids.length}`);slides.push(await request<RasterSlide>('export-slide',{id:ids[i],quality}));}return slides;}
export async function exportPdf(ids:string[],title:string,quality:number,onProgress:(message:string)=>void){const source=await raster(ids,quality,onProgress);const pdf=await PDFDocument.create();for(const item of source){const page=pdf.addPage([item.width,item.height]);const image=await pdf.embedPng(item.bytes);page.drawImage(image,{x:0,y:0,width:item.width,height:item.height});}onProgress('Gerando PDF…');download(await pdf.save(),'application/pdf',clean(title)+'.pdf');}
function hex(value:string,fallback='FFFFFF'){return /^#[0-9a-f]{6}$/i.test(value)?value.slice(1):fallback;}
function addEditableLayer(target:any,layer:Layer,sx:number,sy:number,ox=0,oy=0){const x=(ox+layer.x)*sx,y=(oy+layer.y)*sy,w=Math.max(.01,layer.width*sx),h=Math.max(.01,layer.height*sy);const common={x,y,w,h,rotate:layer.rotation,transparency:Math.round((1-layer.opacity)*100)};
 if(layer.type==='TEXT'&&layer.text!==undefined)target.addText(layer.text,{...common,fontFace:layer.fontFamily||'Arial',fontSize:Math.max(1,(layer.fontSize||16)*.75),bold:(layer.fontWeight||400)>=600,color:hex(layer.fill,'111111'),align:(layer.align||'left') as any,valign:'mid',margin:0,breakLine:false,fit:'shrink'});
 else if(layer.asset)target.addImage({data:layer.asset,...common});
 else if(layer.fill!=='transparent')target.addShape('rect',{...common,fill:{color:hex(layer.fill)},line:{color:hex(layer.fill),transparency:100},radius:(layer.radius||0)*sx});
 for(const child of layer.children)addEditableLayer(target,child,sx,sy,ox+layer.x,oy+layer.y);
}
async function editablePptx(ids:string[],title:string,onProgress:(message:string)=>void){const pptx=new PptxGenJS();pptx.author='figs.dec';pptx.subject='Editable presentation exported from Figma';pptx.title=title;pptx.defineLayout({name:'FIGMA',width:13.333,height:7.5});pptx.layout='FIGMA';
 for(let i=0;i<ids.length;i++){onProgress(`Convertendo elementos editáveis ${i+1}/${ids.length}`);const source=await request<Slide>('parse',{id:ids[i]});const page=pptx.addSlide();page.background={color:hex(source.background)};const scale=Math.min(13.333/source.width,7.5/source.height),w=source.width*scale,h=source.height*scale,dx=(13.333-w)/2,dy=(7.5-h)/2;for(const layer of source.layers)addEditableLayer(page,layer,scale,scale,dx/scale,dy/scale);page.addNotes(source.meta.notes||`Frame do Figma: ${source.name}`);}
 return await pptx.write({outputType:'blob'}) as Blob;
}
export async function exportPptx(ids:string[],title:string,_quality:number,onProgress:(message:string)=>void){const blob=await editablePptx(ids,title,onProgress);onProgress('Gerando PowerPoint editável…');download(blob,'application/vnd.openxmlformats-officedocument.presentationml.presentation',clean(title)+'.pptx');}
export async function exportGoogleSlides(ids:string[],title:string,accessToken:string,onProgress:(message:string)=>void){if(!accessToken.trim())throw new Error('Conecte sua conta Google informando um token OAuth do Google Drive.');const pptx=await editablePptx(ids,title,onProgress);onProgress('Enviando ao Google Apresentações…');const boundary='figs_dec_'+Date.now();const metadata={name:clean(title),mimeType:'application/vnd.google-apps.presentation'};const body=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: application/vnd.openxmlformats-officedocument.presentationml.presentation\r\n\r\n`,pptx,`\r\n--${boundary}--`]);const response=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink',{method:'POST',headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':`multipart/related; boundary=${boundary}`},body});if(!response.ok){const detail=await response.text();throw new Error(`Google Drive recusou a exportação (${response.status}): ${detail.slice(0,180)}`);}const file=await response.json() as {id:string;webViewLink?:string};return file.webViewLink||`https://docs.google.com/presentation/d/${file.id}/edit`;}
export async function exportPngZip(ids:string[],title:string,quality:number,onProgress:(message:string)=>void){const source=await raster(ids,quality,onProgress);const zip=new JSZip();source.forEach((item,index)=>zip.file(`${String(index+1).padStart(2,'0')} - ${clean(item.name)}.png`,item.bytes));onProgress('Compactando imagens…');download(await zip.generateAsync({type:'blob'}),'application/zip',clean(title)+' - PNG.zip');}
function bytesToBase64(bytes:Uint8Array){let binary='';const size=0x8000;for(let i=0;i<bytes.length;i+=size)binary+=String.fromCharCode(...bytes.subarray(i,i+size));return btoa(binary);}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));}
export async function exportWeb(ids:string[],title:string,quality:number,onProgress:(message:string)=>void){const source=await raster(ids,quality,onProgress);const items=source.map((item,i)=>`<section class="slide${i===0?' active':''}" aria-label="Slide ${i+1}"><img src="data:image/png;base64,${bytesToBase64(item.bytes)}" alt="${escapeHtml(item.name)}"></section>`).join('');const html=`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><style>*{box-sizing:border-box}body{margin:0;background:#090b10;color:white;font:14px system-ui;overflow:hidden}.slide{display:none;width:100vw;height:100vh;align-items:center;justify-content:center}.slide.active{display:flex}.slide img{max-width:100%;max-height:100%;object-fit:contain}nav{position:fixed;inset:auto 20px 20px;display:flex;justify-content:center;gap:8px}button{background:#fff;color:#111;border:0;border-radius:999px;padding:10px 18px;font:inherit}</style><body>${items}<nav><button id="prev">←</button><span id="count"></span><button id="next">→</button><button id="full">Tela cheia</button></nav><script>const s=[...document.querySelectorAll('.slide')],c=document.querySelector('#count');let i=0;function show(n){s[i].classList.remove('active');i=(n+s.length)%s.length;s[i].classList.add('active');c.textContent=(i+1)+' / '+s.length}prev.onclick=()=>show(i-1);next.onclick=()=>show(i+1);full.onclick=()=>document.documentElement.requestFullscreen();onkeydown=e=>{if(e.key==='ArrowRight'||e.key===' ')show(i+1);if(e.key==='ArrowLeft')show(i-1);if(e.key==='f')document.documentElement.requestFullscreen()};show(0)</script></body></html>`;download(html,'text/html',clean(title)+'.html');}
